config/routes.rb
Rails.application.routes.draw do
  get 'crestron/index'
  devise_for :users
  root "static_pages#index"
  resources :static_pages
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def after_sign_out_path_for(resource_or_scope)
    request.referrer
  end
end

app/controllers/crestron_controller.rb
class CrestronController < ApplicationController
  require 'redis'

  def index
    redis = Redis.new(host: "localhost")
    @room = redis.get("LSARoom")
    Rails.logger.debug "************************ room #{@room}"
    Rails.logger.debug "************************ room.class #{@room.class}"

    @room_hash = JSON.parse(@room)
    Rails.logger.debug "************************ room_hash #{@room_hash}"

    @room1 = @room_hash['LSARoom']
    Rails.logger.debug "************************ room1 #{@room1}"

  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_static_page, only: %i[ show edit update destroy ]

  # GET /static_pages or /static_pages.json
  def index
    @static_pages = StaticPage.all
  end

  # GET /static_pages/1 or /static_pages/1.json
  def show
  end

  # GET /static_pages/new
  def new
    @static_page = StaticPage.new
  end

  # GET /static_pages/1/edit
  def edit
  end

  # POST /static_pages or /static_pages.json
  def create
    @static_page = StaticPage.new(static_page_params)

    respond_to do |format|
      if @static_page.save
        format.html { redirect_to static_page_url(@static_page), notice: "Static page was successfully created." }
        format.json { render :show, status: :created, location: @static_page }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /static_pages/1 or /static_pages/1.json
  def update
    respond_to do |format|
      if @static_page.update(static_page_params)
        format.html { redirect_to static_page_url(@static_page), notice: "Static page was successfully updated." }
        format.json { render :show, status: :ok, location: @static_page }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @static_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /static_pages/1 or /static_pages/1.json
  def destroy
    @static_page.destroy

    respond_to do |format|
      format.html { redirect_to static_pages_url, notice: "Static page was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_static_page
      @static_page = StaticPage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def static_page_params
      params.fetch(:static_page, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crestron_helper.rb
module CrestronHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/crestron/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Crestron#index</h1>
  <p>LSARoom</p>
  <%= ap(@room1, plain: true, indent: 0).html_safe %>
</div>

app/views/layouts/_header.html.erb
<nav class="flex items-center justify-between flex-wrap bg-blue-800 p-6">
  <div class="flex items-center flex-no-shrink text-white mr-6">
    <svg class="h-8 w-8 mr-2" width="54" height="54" viewBox="0 0 54 54" xmlns="http://www.w3.org/2000/svg"><path d="M13.5 22.1c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05zM0 38.3c1.8-7.2 6.3-10.8 13.5-10.8 10.8 0 12.15 8.1 17.55 9.45 3.6.9 6.75-.45 9.45-4.05-1.8 7.2-6.3 10.8-13.5 10.8-10.8 0-12.15-8.1-17.55-9.45-3.6-.9-6.75.45-9.45 4.05z"/></svg>
    <span class="font-semibold text-xl tracking-tight">AVinator</span>
  </div>
  <div class="block lg:hidden">
    <button class="flex items-center px-3 py-2 border rounded text-teal-lighter border-teal-light hover:text-white hover:border-white">
      <svg class="h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><title>Menu</title><path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z"/></svg>
    </button>
  </div>
  <div class="w-full block flex-grow lg:flex lg:items-center lg:w-auto">
    <div class="text-sm lg:flex-grow">
      <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-blue-300 hover:text-white mr-4">
        Docs
      </a>
      <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-blue-300 hover:text-white mr-4">
        Examples
      </a>
      <a href="#responsive-header" class="block mt-4 lg:inline-block lg:mt-0 text-blue-300 hover:text-white">
        Blog
      </a>
    </div>
    <div class="text-blue-200">
      <% if current_user %>
        <%= current_user.email %>
        <%= button_to "LogOut", destroy_user_session_path, method: :delete, class: "inline-block text-sm px-4 py-2 leading-none border rounded text-white border-white hover:border-transparent hover:text-teal hover:bg-white mt-4 lg:mt-0" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AVinator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/static_pages/_form.html.erb
<%= form_with(model: static_page, class: "contents") do |form| %>
  <% if static_page.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
        <% static_page.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/static_pages/_static_page.html.erb
<div id="<%= dom_id static_page %>">
  <% if action_name != "show" %>
    <%= link_to "Show this static page", static_page, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this static page', edit_static_page_path(static_page), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/static_pages/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing static page</h1>

  <%= render "form", static_page: @static_page %>

  <%= link_to "Show this static page", @static_page, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to static pages", static_pages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/static_pages/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Static pages</h1>
    <%= link_to 'New static page', new_static_page_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="static_pages" class="min-w-full">
    <%= render @static_pages %>
  </div>
</div>

app/views/static_pages/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New static page</h1>

  <%= render "form", static_page: @static_page %>

  <%= link_to 'Back to static pages', static_pages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/static_pages/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @static_page %>

    <%= link_to 'Edit this static_page', edit_static_page_path(@static_page), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this static_page', static_page_path(@static_page), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to static_pages', static_pages_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>